### ISSUE TITLE
Allow configuring what hosts Cyberfeeder runs on

### ISSUE THREAD

**Issue by butzopower** [Rhahi/cyberfeeder#16]
Specifically would be useful to be able to run Cyberfeeder locally / against localhost so that I can confirm local jnet changes won't cause issues with Cyberfeeder.  

Additionally, there's a few other deployments of jnet besides https://jinteki.net with different card pools such as https://reteki.fun/ that I think are often relatively up to date engine/UI wise and so I imagine Cyberfeeder features could work there as well.

**Comment by Rhahi** [comment]
I will do this today. Not sure if Firefox allows localhost, otherwise I can just set something like jinteki.local so that devs can set hosts themselves.

**Comment by Rhahi** [comment]
@butzopower it seems like I can match the whole localhost, but I don't like that it will try to do jnet related features on all localhost websites. I cannot specify ports in manifest.json. Do you think it will be good enough to match "jinteki.local" domain for higher specificity?

**Comment by butzopower** [comment]
Was able to get `jinteki.local` to work with /etc/hosts

<img width="289" alt="image" src="https://github.com/Rhahi/cyberfeeder/assets/5345/19c72b8c-9496-42c7-b860-a27e1ac7875c">

Might be a bit challenging for non-local forks but maybe that's not a huge issue.

**Comment by Rhahi** [comment]
6dcc93c addes jinteki.local and reteki.net, will release when I am done today

**Comment by Rhahi** [comment]
If you suggest more fork websites, I can add them. Current program doesn't support dynamic matching of target websites. It it does, it show up as "access data across all websites", which doesn't sound like a good thing to have for a plugin with limited purposes.
